### ISSUE TITLE
Tooltip not working on gnome?

### ISSUE THREAD

**Issue by Metaxal** [alex-hhh/gui-widget-mixins#1]
I tried the example you gave [here](https://github.com/racket/gui/issues/16) but nothing happens when the mouse hovers over the widgets (even when pausing for a few seconds).

The same example with mred-designer's tooltip (which is likely very similar in code) works:
```racket
#lang racket/gui
(require mred-designer/tooltip
         #;(rename-in gui-widget-mixins [tooltip-mixin tooltip%%]))

(define f (new frame% (label "Test")))
(define b (new (tooltip%% button%) (parent f)
               (label "Hello")
               (tooltip-text "Button")
               #;(tooltip "Button") ))
(define c (new (tooltip%% check-box%) (parent f)
               (label "Hello")
               (tooltip-text "Check Box")
               #;(tooltip "Check Box") ))
(define r (new (tooltip%% radio-box%) (parent f)
               (label "Hello")
               (choices '("a" "b" "c"))
               (tooltip-text "Radio Box")
               #;(tooltip "Radio Box") ))
(send f show #t)
```
so the fix shouldn't be complicated.

I'll try to take a deeper look soonish, unless there's something specific you'd like me to try.

**Comment by alex-hhh** [comment]
Unfortunately, I don't have access to a Linux installation to try this out...  If you want to debug this, the simplest way is to add a few printf statements to methods in "tooltip-mixin.rkt".  I would start with `show-tooltip` and `position-tooltip`, the first one shows/hides the tooltip, the second one moves the tooltip window to follow the cursor.

**Comment by alex-hhh** [comment]
I wonder if the GTK interface only sends an "Enter" event and not a "Motion" event -- the tooltip is shown on motion events only, and at least on windows, this event is received by the control.

https://github.com/alex-hhh/gui-widget-mixins/blob/12770619fd57da3e7dfdf6397fa5ade6817a252e/private/tooltip-mixin.rkt#L124

**Comment by Metaxal** [comment]
Forgot the link to [mreddesigner/tooltip](https://github.com/Metaxal/MrEd-Designer/blob/master/mred-designer/tooltip.rkt)

I tested with this code:
```racket
#lang racket/gui
(require mred-designer/tooltip
         #;(rename-in gui-widget-mixins [tooltip-mixin tooltip%%]))

(define tooltip<%> (interface () ))
(define tooltip%%
  (mixin (subwindow<%>) (tooltip<%>)
    (init-field (tooltip-text " "))
    (define/override (on-subwindow-event w e)
      (displayln (send e get-event-type))
      (super on-subwindow-event w e) 
      #f)
    (super-new)))


(define f (new frame% (label "Test")))
(define b (new (tooltip%% button%) (parent f)
               (label "Hello")
               (tooltip-text "Button")
               #;(tooltip "Button") ))
(define c (new (tooltip%% check-box%) (parent f)
               (label "Hello")
               (tooltip-text "Check Box")
               #;(tooltip "Check Box") ))
(define r (new (tooltip%% radio-box%) (parent f)
               (label "Hello")
               (choices '("a" "b" "c"))
               (tooltip-text "Radio Box")
               #;(tooltip "Radio Box") ))
(send f show #t)
```
and indeed the 'enter and 'leave events are triggered, but not the 'motion ones.

**Comment by alex-hhh** [comment]
This shows that an API is more than just a list of functions and their arguments... 

In any case, it looks like the `'enter` and `'motion` cases will have to be merged into a single branch of the `case` statement.  If you are interested in submitting a pull request I will be happy to accept it, but it not, I'll attempt to fix this over the weekend. 

Also note that this implementation will remove the tool tip if you move the mouse and this is controlled by the `delta-move` parameter, this works nicely on windows.  This feature is intended to allow the user to remove the tooltip in case it obstructs the widget -- might be worth giving it a try on Linux.

Thanks for investigating this,
Alex.

**Comment by Metaxal** [comment]
I'm not sure I'll have time to try to fix it before next week, so don't wait for me.

**Comment by alex-hhh** [comment]
Hi @Metaxal , I pushed an attempted fix on the "ah/pr1" branch, can you please verify that it fixes the issue on Gnome?  Thanks, Alex.

**Comment by Metaxal** [comment]
Yes, problem fixed!
